// Q&A Data for OPA Assistant
const QA_DATA = {
  "Who is One Percent for America (OPA)?": "One Percent for America (OPA) is a national nonprofit. Through our unique online platform, OPA empowers every current and future American to lower the barriers to citizenship. Our affordable digital platform educates immigrants to complete their citizenship journey and successfully settle into American life. At the same time, our platform gives supporters a channel to lend or donate, provide services, and share knowledge. We provide free education and dedicated community support to help build thriving lives in the U.S. for all.",
  
  "How is One Percent for America financed?": "One Percent for America is sponsored by BlueHub Capital, a national nonprofit community finance organization founded in 1985 to address the damage caused by decades of predatory lending practices. Together, we're unified in our goals: Empower immigrants. Celebrate hard work. Accelerate our nation's progress. We invite supporters from across the country to help lower the barriers to citizenship by investing through a loan, donation, or corporate sponsorship.",
  
  "Will OPA share my information with the government?": "One Percent for America will not share or sell your information to third-parties. Only pertinent information will be shared with our Partners or Sponsors as needed if required to complete a purchase, appointment, or application process that you request through our platform. This includes your bank for account verification when borrowing, and credit card processors for donations and lending. Please see our privacy policy for details.",
  
  "How do I contact One Percent for America?": "We would love to hear from you. You can email us at: SupportOPA@onepercentforamerica.org with any questions or feedback. You can also call customer service at 617-404-9797. We are available Monday - Friday from 9:00am - 5:00pm (EST). Our address: One Percent for America, 1785 Columbus Avenue, 6th Floor, Boston, MA 02119",
  
  "Who is eligible to borrow from OPA?": "OPA provides 1% loans to cover the USCIS fees for USCIS paper applications to qualified non-citizen residents with the following statuses and needs: Lawful Permanent Residents (LPRs)/Green Card Holders seeking to apply for US citizenship, DACA (Dreamers) first time applicants and those seeking renewal, Temporary Protected Status (TPS) first time applicants and those seeking renewal. Residents of the following states are not currently eligible for One Percent for America Loan; Arizona, Georgia, Hawaii, Idaho, Louisiana, Mississippi, Missouri, Nevada, New Mexico, North Dakota, Oklahoma, Oregon, Utah, Washington, West Virginia, and Wisconsin. Please check back as this will change soon.",
  
  "How does borrowing from OPA work?": "Eligible immigrants seeking citizenship, citizenship certificate, green card, DACA, and TPS renewals will be able to apply for a 1% interest OPA loan directly at www.onepercentforamerica.org/borrow. Only those submitting applications via mail are eligible for the OPA loan. The OPA loan check cannot be used to fund online applications. You will need to provide your name, email, ACH information for automatic payments (routing and checking account numbers), address and social security number or ITIN, and USCIS A-number. Your loan will be approved if: You are able to provide the information listed above, You know the EXACT dollar amount you need to pay for your USCIS application fee. Knowing the exact amount needed is critical. If the incorrect amount is sent to USCIS your application could be denied. You can verify your email account by receiving and inputting a secure MFA (Multi-Factor Authentication) code, We can verify your bank account information. Prepaid accounts are not valid, If you pass an OFAC verification which helps to ensure OPA can engage in business with the applicant.",
  
  "What are the benefits of an OPA loan?": "Fixed 1% interest rate, Real-time online approval, No application fees, late fees, or penalties for early repayment, 12-month repayment schedule, Freedom to pay early or in larger amounts without penalty, Ability to immediately submit USCIS application paperwork without having cash on hand. Important: Loan checks are payable directly to the U.S. Department of Homeland Security and must be mailed in with your application. They cannot be cashed or used for online applications.",
  
  "How does a borrower repay an OPA loan?": "OPA will draft monthly payments on the 15th day of each month via the borrowers checking account via electronic transfer (ACH). All loans must be paid in full within 1 year of being issued. The payoff of your loan is not dependent on the acceptance or rejection of your application to the USCIS. You can pay more than your minimum monthly payment or pay-off at once without penalties.",
  
  "My loan has been approved—when will I get my check?": "Once your loan is approved, it should take up to 15 business days for you to receive your check in the amount of your loan, via USPS, to the address you listed on your application. If your address changes, please inform us immediately. Checks are made payable to the U.S. Department of Homeland Security directly and must be mailed in with your paper application to the USCIS. Checks cannot be used for online applications. Any misuse of this check, whether deposited or attempted to be used online, constitutes as check fraud and will cause a loan to be reported and canceled.",
  
  "Can I use my OPA loan check for USCIS applications submitted online?": "No. You can use your OPA loan check for paper applications (via mail) ONLY. USCIS does not accept paper checks as a form of payment for online applications.",
  
  "How do I make a one-time loan payment?": "To make a one-time payment, sign-in to your account. Sign-in can be found at the top of any page of the site. Once signed in, go to My Account then to Loan Center. There you will see the option to \"Make a Payment Now\". Loan payments can be made with a U.S.-based debit card. Payments made today are immediately applied to your balance. If you have any questions, please reach out to Customer Service.",
  
  "How do I get my loan documents?": "We now send your loan documents directly to your email address as soon as your loan is approved. If you were approved for a loan before April 26, 2024 or you are unable to locate these documents, please use the form to the right to request copies be sent to you via email.",
  
  "How do I check my loan balance?": "Your loan information, including your balance, is available in the Loan Center. You can access the Loan Center by logging in to your account on www.onepercentforamerica.org and clicking on My Account.",
  
  "How does lending to OPA work?": "People who are interested in lending to One Percent for America can do so by lending money directly on onepercentforamerica.org. Individuals who lend do so for a 24-month period at 0%. At the end of the 24-month period, individuals can decide to renew for another 24 months, donate, or take out money. Lenders will not have the ability to withdraw the money until the end of 24 months.",
  
  "How does donating to OPA work?": "People interested in supporting One Percent for America can do so by donating money directly on onepercentforamerica.org. Individuals who donate can do so on a one-time or monthly basis. Donations are tax-deductible. Individuals who donate will receive a confirmation and donation receipt via email.",
  
  "I made a donation but did not receive a receipt. What should I do?": "You should have received an email the same day you made your donation. Please check your SPAM folder. If you do not find it there, please email supportOPA@onepercentforamerica.org and we will resend you the information.",
  
  "What is the mailing address for donations?": "Donations can be mailed to: One Percent for America c/o BlueHub Capital, 1785 Columbus Avenue, 6th Floor, Boston, MA 02119",
  
  "How can I or my organization refer borrowers to OPA?": "Thank you in advance for your interest and support. Visit onepercentforamerica/borrow for eligibility requirements and the benefits of an OPA loan for immigrants seeking citizenship. This would be a great starting place for any potential borrowers you would like to refer to learn a bit more about the loans before applying.",
  
  "How can my organization partner or collaborate with OPA?": "The OPA team looks forward to hearing from you. Whether it is a webinar for your colleagues or clients, an in-person meeting, a phone call, or an invitation to attend an event, we can discuss how to best work together to amplify our aligned work and missions. For more information, please contact our Director of Corporate Partnerships & Development: nsharpe@onepercentforamerica.org",
  
  "How do I become a Partner, Sponsor, or Provider?": "Becoming a sponsor or provider within OPA's platform provides a unique opportunity to advance the goals of immigrants all across the country, support immigrants within your entity, and raise the profile of your entity's commitment to OPA's mission to unite people across the United States at all stages of citizenship to invest in a resilient, inclusive country and collectively advocate to lower the barriers to citizenship. Nonprofit organizations and companies who are mission-aligned are welcome to partner with us through sponsorship levels or partner offerings, sharing branded educational materials, one-on-one virtual services, unique subject matter interviews, videos, or events. OPA and its partners work together to curate existing, trusted content and services, and to design innovative solutions across tech, media, and education, that will significantly improve the connection of resources, users, and providers. For more information, please contact our Director of Corporate Partnerships & Development: nsharpe@onepercentforamerica.org",
  
  "How can I refer a client for an OPA loan?": "OPA works with partner organizations across the U.S. to ensure that individuals are aware of the 1% interest loan for USCIS application fees. Providers or referral organizations do not have to provide any special documentation; they can simply direct their clients to the OPA website. Contact us if you would like flyers to share with your community. For more information, please contact our Director of Corporate Partnerships & Development: nsharpe@onepercentforamerica.org"
};